# Generated by Django 4.0.3 on 2022-03-10 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CoinAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_wallet_address', models.CharField(max_length=500)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coin')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='usercryptodetails',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.balance'),
        ),
        migrations.AlterField(
            model_name='usercryptodetails',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coin'),
        ),
    ]
