# Generated by Django 4.0.3 on 2022-03-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_coin_coinaddress_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
