# Generated by Django 4.0 on 2022-04-02 06:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_facebooklink_instagramlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowToInvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_one', models.CharField(max_length=500)),
                ('content_one', ckeditor.fields.RichTextField()),
                ('title_two', models.CharField(max_length=500)),
                ('content_two', ckeditor.fields.RichTextField()),
                ('title_three', models.CharField(max_length=500)),
                ('content_three', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
