# Generated by Django 4.0 on 2022-04-02 07:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_howtoinvest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='howtoinvest',
            name='content_three',
        ),
        migrations.RemoveField(
            model_name='howtoinvest',
            name='content_two',
        ),
        migrations.RemoveField(
            model_name='howtoinvest',
            name='title_three',
        ),
        migrations.RemoveField(
            model_name='howtoinvest',
            name='title_two',
        ),
    ]
