# Generated by Django 4.0.3 on 2022-03-13 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('maximum_stake', models.DecimalField(decimal_places=2, max_digits=6)),
                ('minimum_stake', models.DecimalField(decimal_places=2, max_digits=3)),
                ('roi', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('balance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.balance')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.package')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.investmentstatus')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
