# Generated by Django 4.0.3 on 2022-03-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='maximum_stake',
            field=models.DecimalField(decimal_places=6, max_digits=6),
        ),
        migrations.AlterField(
            model_name='package',
            name='minimum_stake',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
    ]
