# Generated by Django 4.0.3 on 2022-03-09 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_investmentstatus_invest_status'),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.investmentstatus'),
        ),
    ]
