# Generated by Django 4.0.3 on 2022-03-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_package_maximum_stake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='maximum_stake',
            field=models.PositiveIntegerField(default='000000', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='minimum_stake',
            field=models.PositiveIntegerField(default='000.00', null=True),
        ),
    ]
