# Generated by Django 4.0.3 on 2022-03-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_alter_investment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='sn',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
