# Generated by Django 4.0.3 on 2022-03-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_investment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
