# Generated by Django 4.0.3 on 2022-03-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_alter_investment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('N', 'Unactive')], max_length=20),
        ),
    ]
