# Generated by Django 4.0 on 2022-05-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_alter_investment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Unactive')], max_length=20),
        ),
    ]
