# Generated by Django 4.0.3 on 2022-03-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_balance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercryptodetails',
            name='coin',
            field=models.CharField(max_length=400),
        ),
    ]
