# Generated by Django 4.0.3 on 2022-03-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usercryptodetails_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercryptodetails',
            name='balance',
        ),
    ]
