# Generated by Django 4.0.3 on 2022-03-21 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_usercryptodetails_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercryptodetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
