# Generated by Django 4.0.3 on 2022-03-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usercryptodetails_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_email', models.EmailField(max_length=254)),
                ('msg', models.CharField(max_length=50)),
            ],
        ),
    ]
