# Generated by Django 4.0.3 on 2022-03-21 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='balance',
        ),
    ]
