# Generated by Django 4.0.3 on 2022-03-10 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_coin_coinaddress_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_alter_investmentstatus_invest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositstatus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentstatus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawstatus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.balance')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coinaddress')),
                ('status', models.ForeignKey(choices=[('P', 'Pending'), ('F', 'Failed'), ('C', 'Completed')], null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.withdrawstatus')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('proof', models.ImageField(upload_to='')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coin')),
                ('company_wallet_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coinaddress')),
                ('status', models.ForeignKey(choices=[('P', 'Pending'), ('F', 'Failed'), ('C', 'Completed')], null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.depositstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
