# Generated by Django 4.0.3 on 2022-03-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_withdraw_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('N', 'Unactive')], max_length=20, null=True),
        ),
    ]
