# Generated by Django 4.0.3 on 2022-03-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_alter_investment_status'),
        ('transactions', '0003_alter_withdraw_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investments.package'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('F', 'Failed'), ('C', 'Completed')], default='status', max_length=20),
        ),
    ]
