# Generated by Django 4.0.3 on 2022-03-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_deposit_package_alter_deposit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='proof',
            field=models.CharField(max_length=800),
        ),
    ]
