# Generated by Django 4.0.3 on 2022-03-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_deposit_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
