# Generated by Django 4.0.3 on 2022-03-09 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_investmentstatus_invest_status'),
        ('useraccounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='status',
            field=models.ForeignKey(choices=[('P', 'Pending'), ('F', 'Failed'), ('C', 'Completed')], null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.depositstatus'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='status',
            field=models.ForeignKey(choices=[('P', 'Pending'), ('F', 'Failed'), ('C', 'Completed')], null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.withdrawstatus'),
        ),
    ]
