# Generated by Django 3.2.11 on 2022-03-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_deposit_status_withdraw_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
