# Generated by Django 3.2.11 on 2022-03-10 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useraccounts', '0004_withdraw_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCryptoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=500)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccounts.balance')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccounts.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
