# Generated by Django 4.0.3 on 2022-03-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_coin_coinaddress_balance_and_more'),
        ('investments', '0004_alter_investment_balance'),
        ('useraccounts', '0005_usercryptodetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinaddress',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='company_wallet_address',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercryptodetails',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='usercryptodetails',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='usercryptodetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='status',
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.DeleteModel(
            name='Coin',
        ),
        migrations.DeleteModel(
            name='CoinAddress',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='UserCryptoDetails',
        ),
        migrations.DeleteModel(
            name='Withdraw',
        ),
    ]
